### ISSUE TITLE
Outdated? 

### ISSUE THREAD

**Issue by ANorseDude** [jaredhanson/passport-instagram#17]
Can't get it to work at all - is it outdated?

**Comment by mwilc0x** [comment]
I was able to get something mostly working. I can push something live if you still need a reference!

**Comment by sylvesteraswin** [comment]
@mjw56 can you push an example?

I tried this plugin but I wasn't able to get it to work. It would be of great help if you can show an example.

**Comment by ANorseDude** [comment]
I dumped this and used https://github.com/sahat/hackathon-starter solution instead. the hackathon is up to date and is revised when something changes. Passport-instagram can be used but, well,. you need to revive the code and updated it.
