### ISSUE TITLE
Passport strategy not working.

### ISSUE THREAD

**Issue by youfoundron** [jaredhanson/passport-instagram#4]
The following error is being logged on callback. It looks like this is causing several apps to break. 

`failed to fetch user profile (status: 400 data: {"meta":{"error_type":"OAuthParameterException","code":400,"error_message":"Missing client_id or access_token URL parameter."}})`

Could very well be on Instagram's end.

**Comment by apaternite** [comment]
Mine stopped working as well.

**Comment by youfoundron** [comment]
This was due to a temporary issue with Instagram's servers and is no longer a problem.
