### ISSUE TITLE
failureRedirect runs even on success

### ISSUE THREAD

**Issue by stanleycyang** [jaredhanson/passport-instagram#6]
``` js

router.get('/instagram', passport.authenticate('instagram'));

router.get('/instagram/callback', passport.authenticate('instagram', {
  failureRedirect: '/'
}), function(req, res){
  res.redirect('/config');
});

```

The failureRedirect is the one that always runs even when it's successful

**Comment by jaredhanson** [comment]
I cannot reproduce this. Are you certain that authentication was actually successful?

**Comment by stanleycyang** [comment]
Yes. I get the token back and the user's info prints out in the server log plus they are saved in the DB. It's really odd

**Comment by jaredhanson** [comment]
Can you provide a short, runnable script that reproduces this?

**Comment by stanleycyang** [comment]
It's currently in a private repo. Let me see if I can replicate this after I finish this current project!

**Comment by stanleycyang** [comment]
My `done()` wasn't returning a user, and I just wrote in some calls to my MongoDB and its a non-issue. Thanks!
